### ISSUE TITLE
Second text box gives students an error.

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#84] opened 2021-03-20 17:15 UTC
# Module:3 Clean, Transform, and Load Data In Power BI
#### Step: 8. For your convenience,...
![Step 8](https://user-images.githubusercontent.com/53623295/111878087-06076f80-897d-11eb-9b6e-a93f01bf2594.png)

Description of issue
Consider removing the 2nd text box. Students will think they need type this code. The student only need to type (insert) from the first text box. The second text box, as is, gives an error and they cannot continue.
IF you wanted them to type this comment in the code, comments should be in the format of /* adfadfasdf */
Repro steps:

1.Remove the second text box and put this info in a Tip: format for the student to read.
1.
1.

**Comment by shannonlindsay** [comment] 2021-03-22 13:43
Hi @FraSkills3362 - similar to issue #85 - I don't see this issue in the markdown itself. Can you let me know which lab environment this screenshot is from? Thanks!
![image](https://user-images.githubusercontent.com/77289548/111999046-f90c8c80-8af2-11eb-8892-db7eba68b129.png)

**Comment by shannonlindsay** [comment] 2021-03-22 20:47
Thanks @FraSkills3362 for flagging this. I had a formatting issue in the markdown - the issue is now fixed. Thanks again!

**Closed by shannonlindsay** 2021-03-22 20:47 UTC
