### ISSUE TITLE
lab "Design a Report in Power BI Desktop, Part 2" image not displayed

### ISSUE THREAD

**Issue by bulcke** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#136] opened 2021-07-14 11:03 UTC
# Module: 00
#### Step: 00

Description of issue

Introduction for this exercise is this

"Exercise 2: Configure Drill Through

In this exercise you will create a new page and configure it as a drill through page. When you've completed the design, the page will look like the following:
"

But no image is displayed.

**Comment by shannonlindsay** [comment] 2021-07-27 15:13
@bulcke - I am able to see the image here in GitHub. Can you please elaborate? Is this in the LODS environment that you're unable to see the image? Thanks for your help!

![image](https://user-images.githubusercontent.com/77289548/127179831-a07a676a-fafd-457c-a3e9-f3f279ba047a.png)

**Comment by shannonlindsay** [comment] 2021-08-02 13:31
Closing this issue as I cannot reproduce. @bulcke - please let me know if you're still having issues.

**Closed by shannonlindsay** 2021-08-02 13:31 UTC
