### ISSUE TITLE
Relationship already exists

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#132] opened 2021-06-02 02:27 UTC
# Module: 04
#### Step: 08-19

Description of issue
Relationship already exists, does not need to create or else an error appears.

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment] 2021-06-02 14:41
Hi @mhykgyver - I'd like to be sure I am understanding your issue correctly. Steps 8-19 are showing students how to edit relationships, change the cross filter direction and security filters, and make a relationship inactive.  Can you provide clarity on what the problem is for you? You are correct that you will get an error if you try to establish the relationship again, because you can only have one active relationship between two tables.

**Comment by shannonlindsay** [comment] 2021-06-08 22:02
@mhykgyver - I am closing this issue. Please feel free to comment below if my note above does not respond to your question.

**Closed by shannonlindsay** 2021-06-08 22:02 UTC
