### ISSUE TITLE
Wrong formating M04L01T02S05, S06, S24

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#173] opened 2022-01-26 12:12 UTC
# Module: 04
#### Step: 04, 05, 24

Formating of instructions is confusing. Special if you have small screen. See attachment.

<img width="665" alt="M04L01T02S05" src="https://user-images.githubusercontent.com/4288542/151160576-04066e99-353d-4532-b15f-46ec4ba4aa3f.png">

<img width="702" alt="M04L01T02S24" src="https://user-images.githubusercontent.com/4288542/151160879-276720b1-3596-4721-97f6-e927106ffbb3.png">

**Comment by bechynsky** [comment] 2022-01-26 12:22
It looks like problem with github.io version of labs. Formatting on Github is correct. I suggest to change | character to different separator.

<img width="784" alt="M04L01T02S05_correct" src="https://user-images.githubusercontent.com/4288542/151162111-c72f4db7-6a63-466a-b6b2-87a0f867842c.png">

**Comment by bpmoring** [comment] 2022-01-26 18:45
Hi @bechynsky, this has been an issue that is addressed elsewhere in the labs. It is a simple adjustment in the markdown to fix the formatting. Thank you for bringing this to my attention, I will get this corrected.

**Comment by VitalyMCT** [comment] 2022-01-28 22:11
This is actually a duplicate of #161, which was closed yet not (fully) resolved.

**Comment by bpmoring** [comment] 2022-01-28 22:37
Hi @bechynsky, I do not see this issue that you mentioned above in the labs. We addressed this issue indicated above by @VitalyMCT

**Comment by VitalyMCT** [comment] 2022-01-28 22:40
@bpmoring No, the issue I raised is still there. Take a look at the link, you will see it.

**Comment by bpmoring** [comment] 2022-01-28 22:55
These items were not showing up in the markdown version, but I was able to locate them using the link in the issue @VitalyMCT had above. I have updated the markdown in each lab, and you should see the resolved issue reflected across all labs soon.

**Closed** 2022-01-28 23:03 UTC
