### ISSUE TITLE
Lab 6 is already completed in the starter file

### ISSUE THREAD

**Issue by mttturek** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#91] opened 2021-03-23 18:36 UTC
# Module: 00
#### Step: 00

Description of issue:
 Self explanatory, the starter has the work all done already.
Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment] 2021-04-29 20:26
@mttturek - are you referring to Lab 6 - Create DAX Calculations in Power BI Desktop, Part 2? The starter file should have 2 pages with visuals on it, and learners begin by adding a matrix on Page 3. Can you please confirm this is what you're seeing? I am not seeing this.

**Comment by shannonlindsay** [comment] 2021-04-30 19:44
Closing this issue as I am unable to reproduce.

**Closed by shannonlindsay** 2021-04-30 19:44 UTC
