### ISSUE TITLE
Numbering problem in the steps

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#85] opened 2021-03-20 17:17 UTC
# Module:3 Clean, Transform, and Load Data In Power BI
#### Step: 8. For your convenience,...
![Step 8](https://user-images.githubusercontent.com/53623295/111878087-06076f80-897d-11eb-9b6e-a93f01bf2594.png)

Description of issue
Numbering problem in the steps. It seems the numbering went from step 8 to step 1. The step for "OK" should be numbered 9.
Repro steps:

1. Continue the numbering from step 8 to the following steps.
1.
1.

**Comment by shannonlindsay** [comment] 2021-03-22 13:41
Hi @FraSkills3362 - thanks for your feedback. I don't see this numbering issue in the markdown file - so I'll need to do a little research to understand the cause of the problem. Which lab hosting environment is this screenshot from?
![image](https://user-images.githubusercontent.com/77289548/111998794-bc409580-8af2-11eb-9bc4-1798bb38554a.png)

**Comment by FraSkills3362** [comment] 2021-03-22 14:30
I am with New Horizons Computer Learning center. Who we use is determined by Corporate, but from what I can tell, we use Learn on Demand Solutions. 
![Learn on Demand logo](https://user-images.githubusercontent.com/53623295/112005883-8d79ed80-8af9-11eb-8481-28f252004d88.png)

**Comment by FraSkills3362** [comment] 2021-03-22 14:32
I am with New Horizons Computer Learning center. Who we use is determined by Corporate, but from what I can tell, we use Learn on Demand Solutions.
[Learn on Demand logo]<https://user-images.githubusercontent.com/53623295/112005883-8d79ed80-8af9-11eb-8481-28f252004d88.png>


[Logo, company name  Description automatically generated]

Beverlee Frazier | IT Training Specialist

**Comment by shannonlindsay** [comment] 2021-03-24 18:57
thanks for the additional detail @FraSkills3362 - this was being caused by some formatting issues in the markdown file and it is now fixed. You'll see that update live on the 26th of March. Thanks for your help.

**Closed by shannonlindsay** 2021-03-24 18:57 UTC
